declare module "lucide-react" {
  import type { ComponentType } from "react";

  type IconProps = {
    className?: string;
    size?: number;
    strokeWidth?: number;
    "aria-hidden"?: boolean | string;
  };
  export type LucideIcon = ComponentType<IconProps>;

  export const Activity: ComponentType<IconProps>;
  export const Ambulance: ComponentType<IconProps>;
  export const AlertCircle: ComponentType<IconProps>;
  export const ArrowUpRight: ComponentType<IconProps>;
  export const BedDouble: ComponentType<IconProps>;
  export const Bell: ComponentType<IconProps>;
  export const Building2: ComponentType<IconProps>;
  export const CalendarCheck: ComponentType<IconProps>;
  export const CalendarCheck2: ComponentType<IconProps>;
  export const Check: ComponentType<IconProps>;
  export const CheckCircle2: ComponentType<IconProps>;
  export const ChevronDown: ComponentType<IconProps>;
  export const ChevronRight: ComponentType<IconProps>;
  export const ArrowLeft: ComponentType<IconProps>;
  export const ArrowRight: ComponentType<IconProps>;
  export const Clock: ComponentType<IconProps>;
  export const CreditCard: ComponentType<IconProps>;
  export const Download: ComponentType<IconProps>;
  export const Droplet: ComponentType<IconProps>;
  export const Filter: ComponentType<IconProps>;
  export const FileText: ComponentType<IconProps>;
  export const FlaskConical: ComponentType<IconProps>;
  export const Globe: ComponentType<IconProps>;
  export const HeartPulse: ComponentType<IconProps>;
  export const HelpCircle: ComponentType<IconProps>;
  export const Hourglass: ComponentType<IconProps>;
  export const IdCard: ComponentType<IconProps>;
  export const Inbox: ComponentType<IconProps>;
  export const LayoutDashboard: ComponentType<IconProps>;
  export const LocateFixed: ComponentType<IconProps>;
  export const Loader2: ComponentType<IconProps>;
  export const LogOut: ComponentType<IconProps>;
  export const MapPin: ComponentType<IconProps>;
  export const MessageSquare: ComponentType<IconProps>;
  export const Hospital: ComponentType<IconProps>;
  export const PhoneCall: ComponentType<IconProps>;
  export const Phone: ComponentType<IconProps>;
  export const Plus: ComponentType<IconProps>;
  export const Search: ComponentType<IconProps>;
  export const Send: ComponentType<IconProps>;
  export const ServerCog: ComponentType<IconProps>;
  export const Settings: ComponentType<IconProps>;
  export const Shield: ComponentType<IconProps>;
  export const ShieldAlert: ComponentType<IconProps>;
  export const ShieldCheck: ComponentType<IconProps>;
  export const Siren: ComponentType<IconProps>;
  export const Sparkles: ComponentType<IconProps>;
  export const Stethoscope: ComponentType<IconProps>;
  export const Tag: ComponentType<IconProps>;
  export const Trash2: ComponentType<IconProps>;
  export const Truck: ComponentType<IconProps>;
  export const TrendingUp: ComponentType<IconProps>;
  export const Upload: ComponentType<IconProps>;
  export const User: ComponentType<IconProps>;
  export const Users: ComponentType<IconProps>;
  export const UserRound: ComponentType<IconProps>;
  export const UserRoundPlus: ComponentType<IconProps>;
  export const Pencil: ComponentType<IconProps>;
  export const Wallet: ComponentType<IconProps>;
  export const WalletCards: ComponentType<IconProps>;
  export const X: ComponentType<IconProps>;
}