/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as AmbulanceIndexRouteImport } from './routes/ambulance.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientTrackingRouteImport } from './routes/patient.tracking'
import { Route as PatientSosRouteImport } from './routes/patient.sos'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPreferencesRouteImport } from './routes/patient.preferences'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientAuthRouteImport } from './routes/patient.auth'
import { Route as PatientAiRouteImport } from './routes/patient.ai'
import { Route as PatientActivityRouteImport } from './routes/patient.activity'
import { Route as HospitalStaffRouteImport } from './routes/hospital.staff'
import { Route as HospitalReservationsRouteImport } from './routes/hospital.reservations'
import { Route as HospitalRequestsRouteImport } from './routes/hospital.requests'
import { Route as HospitalPaymentsRouteImport } from './routes/hospital.payments'
import { Route as HospitalEmergenciesRouteImport } from './routes/hospital.emergencies'
import { Route as HospitalDiagnosticsRouteImport } from './routes/hospital.diagnostics'
import { Route as HospitalConsultationsRouteImport } from './routes/hospital.consultations'
import { Route as HospitalBloodRouteImport } from './routes/hospital.blood'
import { Route as HospitalBedsRouteImport } from './routes/hospital.beds'
import { Route as HospitalAnalyticsRouteImport } from './routes/hospital.analytics'
import { Route as HospitalAmbulancesRouteImport } from './routes/hospital.ambulances'
import { Route as AmbulanceTripRouteImport } from './routes/ambulance.trip'
import { Route as AmbulanceSplashRouteImport } from './routes/ambulance.splash'
import { Route as AmbulanceProfileRouteImport } from './routes/ambulance.profile'
import { Route as AmbulanceNotificationsRouteImport } from './routes/ambulance.notifications'
import { Route as AmbulanceNavigateRouteImport } from './routes/ambulance.navigate'
import { Route as AmbulanceHistoryRouteImport } from './routes/ambulance.history'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PatientHospitalsIndexRouteImport } from './routes/patient.hospitals.index'
import { Route as PatientAuthIndexRouteImport } from './routes/patient.auth.index'
import { Route as PatientHospitalsIdRouteImport } from './routes/patient.hospitals.$id'
import { Route as PatientAuthStatesRouteImport } from './routes/patient.auth.states'
import { Route as PatientAuthSplashRouteImport } from './routes/patient.auth.splash'
import { Route as PatientAuthSignupRouteImport } from './routes/patient.auth.signup'
import { Route as PatientAuthOnboardingRouteImport } from './routes/patient.auth.onboarding'
import { Route as PatientAuthLoginRouteImport } from './routes/patient.auth.login'
import { Route as PatientAuthForgotRouteImport } from './routes/patient.auth.forgot'
import { Route as PatientAuthDriverSignupRouteImport } from './routes/patient.auth.driver-signup'
import { Route as PatientAuthAccountTypeRouteImport } from './routes/patient.auth.account-type'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const AmbulanceIndexRoute = AmbulanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientTrackingRoute = PatientTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSosRoute = PatientSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPreferencesRoute = PatientPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAuthRoute = PatientAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAiRoute = PatientAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PatientRoute,
} as any)
const PatientActivityRoute = PatientActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PatientRoute,
} as any)
const HospitalStaffRoute = HospitalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalReservationsRoute = HospitalReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalRequestsRoute = HospitalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalPaymentsRoute = HospitalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalEmergenciesRoute = HospitalEmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalDiagnosticsRoute = HospitalDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalConsultationsRoute = HospitalConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalBloodRoute = HospitalBloodRouteImport.update({
  id: '/blood',
  path: '/blood',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalBedsRoute = HospitalBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAnalyticsRoute = HospitalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAmbulancesRoute = HospitalAmbulancesRouteImport.update({
  id: '/ambulances',
  path: '/ambulances',
  getParentRoute: () => HospitalRoute,
} as any)
const AmbulanceTripRoute = AmbulanceTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AmbulanceSplashRoute = AmbulanceSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AmbulanceProfileRoute = AmbulanceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AmbulanceNotificationsRoute = AmbulanceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AmbulanceNavigateRoute = AmbulanceNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AmbulanceHistoryRoute = AmbulanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AmbulanceRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PatientHospitalsIndexRoute = PatientHospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAuthIndexRoute = PatientAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientHospitalsIdRoute = PatientHospitalsIdRouteImport.update({
  id: '/hospitals/$id',
  path: '/hospitals/$id',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAuthStatesRoute = PatientAuthStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthSplashRoute = PatientAuthSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthSignupRoute = PatientAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthOnboardingRoute = PatientAuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthLoginRoute = PatientAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthForgotRoute = PatientAuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthDriverSignupRoute = PatientAuthDriverSignupRouteImport.update({
  id: '/driver-signup',
  path: '/driver-signup',
  getParentRoute: () => PatientAuthRoute,
} as any)
const PatientAuthAccountTypeRoute = PatientAuthAccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => PatientAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ambulance': typeof AmbulanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/ambulance/history': typeof AmbulanceHistoryRoute
  '/ambulance/navigate': typeof AmbulanceNavigateRoute
  '/ambulance/notifications': typeof AmbulanceNotificationsRoute
  '/ambulance/profile': typeof AmbulanceProfileRoute
  '/ambulance/splash': typeof AmbulanceSplashRoute
  '/ambulance/trip': typeof AmbulanceTripRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/blood': typeof HospitalBloodRoute
  '/hospital/consultations': typeof HospitalConsultationsRoute
  '/hospital/diagnostics': typeof HospitalDiagnosticsRoute
  '/hospital/emergencies': typeof HospitalEmergenciesRoute
  '/hospital/payments': typeof HospitalPaymentsRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/reservations': typeof HospitalReservationsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/auth': typeof PatientAuthRouteWithChildren
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/preferences': typeof PatientPreferencesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/sos': typeof PatientSosRoute
  '/patient/tracking': typeof PatientTrackingRoute
  '/admin/': typeof AdminIndexRoute
  '/ambulance/': typeof AmbulanceIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/auth/account-type': typeof PatientAuthAccountTypeRoute
  '/patient/auth/driver-signup': typeof PatientAuthDriverSignupRoute
  '/patient/auth/forgot': typeof PatientAuthForgotRoute
  '/patient/auth/login': typeof PatientAuthLoginRoute
  '/patient/auth/onboarding': typeof PatientAuthOnboardingRoute
  '/patient/auth/signup': typeof PatientAuthSignupRoute
  '/patient/auth/splash': typeof PatientAuthSplashRoute
  '/patient/auth/states': typeof PatientAuthStatesRoute
  '/patient/hospitals/$id': typeof PatientHospitalsIdRoute
  '/patient/auth/': typeof PatientAuthIndexRoute
  '/patient/hospitals/': typeof PatientHospitalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/ambulance/history': typeof AmbulanceHistoryRoute
  '/ambulance/navigate': typeof AmbulanceNavigateRoute
  '/ambulance/notifications': typeof AmbulanceNotificationsRoute
  '/ambulance/profile': typeof AmbulanceProfileRoute
  '/ambulance/splash': typeof AmbulanceSplashRoute
  '/ambulance/trip': typeof AmbulanceTripRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/blood': typeof HospitalBloodRoute
  '/hospital/consultations': typeof HospitalConsultationsRoute
  '/hospital/diagnostics': typeof HospitalDiagnosticsRoute
  '/hospital/emergencies': typeof HospitalEmergenciesRoute
  '/hospital/payments': typeof HospitalPaymentsRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/reservations': typeof HospitalReservationsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/preferences': typeof PatientPreferencesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/sos': typeof PatientSosRoute
  '/patient/tracking': typeof PatientTrackingRoute
  '/admin': typeof AdminIndexRoute
  '/ambulance': typeof AmbulanceIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/auth/account-type': typeof PatientAuthAccountTypeRoute
  '/patient/auth/driver-signup': typeof PatientAuthDriverSignupRoute
  '/patient/auth/forgot': typeof PatientAuthForgotRoute
  '/patient/auth/login': typeof PatientAuthLoginRoute
  '/patient/auth/onboarding': typeof PatientAuthOnboardingRoute
  '/patient/auth/signup': typeof PatientAuthSignupRoute
  '/patient/auth/splash': typeof PatientAuthSplashRoute
  '/patient/auth/states': typeof PatientAuthStatesRoute
  '/patient/hospitals/$id': typeof PatientHospitalsIdRoute
  '/patient/auth': typeof PatientAuthIndexRoute
  '/patient/hospitals': typeof PatientHospitalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ambulance': typeof AmbulanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/ambulance/history': typeof AmbulanceHistoryRoute
  '/ambulance/navigate': typeof AmbulanceNavigateRoute
  '/ambulance/notifications': typeof AmbulanceNotificationsRoute
  '/ambulance/profile': typeof AmbulanceProfileRoute
  '/ambulance/splash': typeof AmbulanceSplashRoute
  '/ambulance/trip': typeof AmbulanceTripRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/blood': typeof HospitalBloodRoute
  '/hospital/consultations': typeof HospitalConsultationsRoute
  '/hospital/diagnostics': typeof HospitalDiagnosticsRoute
  '/hospital/emergencies': typeof HospitalEmergenciesRoute
  '/hospital/payments': typeof HospitalPaymentsRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/reservations': typeof HospitalReservationsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/auth': typeof PatientAuthRouteWithChildren
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/preferences': typeof PatientPreferencesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/sos': typeof PatientSosRoute
  '/patient/tracking': typeof PatientTrackingRoute
  '/admin/': typeof AdminIndexRoute
  '/ambulance/': typeof AmbulanceIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/auth/account-type': typeof PatientAuthAccountTypeRoute
  '/patient/auth/driver-signup': typeof PatientAuthDriverSignupRoute
  '/patient/auth/forgot': typeof PatientAuthForgotRoute
  '/patient/auth/login': typeof PatientAuthLoginRoute
  '/patient/auth/onboarding': typeof PatientAuthOnboardingRoute
  '/patient/auth/signup': typeof PatientAuthSignupRoute
  '/patient/auth/splash': typeof PatientAuthSplashRoute
  '/patient/auth/states': typeof PatientAuthStatesRoute
  '/patient/hospitals/$id': typeof PatientHospitalsIdRoute
  '/patient/auth/': typeof PatientAuthIndexRoute
  '/patient/hospitals/': typeof PatientHospitalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ambulance'
    | '/auth'
    | '/hospital'
    | '/patient'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/users'
    | '/admin/verification'
    | '/ambulance/history'
    | '/ambulance/navigate'
    | '/ambulance/notifications'
    | '/ambulance/profile'
    | '/ambulance/splash'
    | '/ambulance/trip'
    | '/hospital/ambulances'
    | '/hospital/analytics'
    | '/hospital/beds'
    | '/hospital/blood'
    | '/hospital/consultations'
    | '/hospital/diagnostics'
    | '/hospital/emergencies'
    | '/hospital/payments'
    | '/hospital/requests'
    | '/hospital/reservations'
    | '/hospital/staff'
    | '/patient/activity'
    | '/patient/ai'
    | '/patient/auth'
    | '/patient/notifications'
    | '/patient/preferences'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/sos'
    | '/patient/tracking'
    | '/admin/'
    | '/ambulance/'
    | '/hospital/'
    | '/patient/'
    | '/patient/auth/account-type'
    | '/patient/auth/driver-signup'
    | '/patient/auth/forgot'
    | '/patient/auth/login'
    | '/patient/auth/onboarding'
    | '/patient/auth/signup'
    | '/patient/auth/splash'
    | '/patient/auth/states'
    | '/patient/hospitals/$id'
    | '/patient/auth/'
    | '/patient/hospitals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/users'
    | '/admin/verification'
    | '/ambulance/history'
    | '/ambulance/navigate'
    | '/ambulance/notifications'
    | '/ambulance/profile'
    | '/ambulance/splash'
    | '/ambulance/trip'
    | '/hospital/ambulances'
    | '/hospital/analytics'
    | '/hospital/beds'
    | '/hospital/blood'
    | '/hospital/consultations'
    | '/hospital/diagnostics'
    | '/hospital/emergencies'
    | '/hospital/payments'
    | '/hospital/requests'
    | '/hospital/reservations'
    | '/hospital/staff'
    | '/patient/activity'
    | '/patient/ai'
    | '/patient/notifications'
    | '/patient/preferences'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/sos'
    | '/patient/tracking'
    | '/admin'
    | '/ambulance'
    | '/hospital'
    | '/patient'
    | '/patient/auth/account-type'
    | '/patient/auth/driver-signup'
    | '/patient/auth/forgot'
    | '/patient/auth/login'
    | '/patient/auth/onboarding'
    | '/patient/auth/signup'
    | '/patient/auth/splash'
    | '/patient/auth/states'
    | '/patient/hospitals/$id'
    | '/patient/auth'
    | '/patient/hospitals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ambulance'
    | '/auth'
    | '/hospital'
    | '/patient'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/users'
    | '/admin/verification'
    | '/ambulance/history'
    | '/ambulance/navigate'
    | '/ambulance/notifications'
    | '/ambulance/profile'
    | '/ambulance/splash'
    | '/ambulance/trip'
    | '/hospital/ambulances'
    | '/hospital/analytics'
    | '/hospital/beds'
    | '/hospital/blood'
    | '/hospital/consultations'
    | '/hospital/diagnostics'
    | '/hospital/emergencies'
    | '/hospital/payments'
    | '/hospital/requests'
    | '/hospital/reservations'
    | '/hospital/staff'
    | '/patient/activity'
    | '/patient/ai'
    | '/patient/auth'
    | '/patient/notifications'
    | '/patient/preferences'
    | '/patient/profile'
    | '/patient/settings'
    | '/patient/sos'
    | '/patient/tracking'
    | '/admin/'
    | '/ambulance/'
    | '/hospital/'
    | '/patient/'
    | '/patient/auth/account-type'
    | '/patient/auth/driver-signup'
    | '/patient/auth/forgot'
    | '/patient/auth/login'
    | '/patient/auth/onboarding'
    | '/patient/auth/signup'
    | '/patient/auth/splash'
    | '/patient/auth/states'
    | '/patient/hospitals/$id'
    | '/patient/auth/'
    | '/patient/hospitals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmbulanceRoute: typeof AmbulanceRouteWithChildren
  AuthRoute: typeof AuthRoute
  HospitalRoute: typeof HospitalRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/ambulance/': {
      id: '/ambulance/'
      path: '/'
      fullPath: '/ambulance/'
      preLoaderRoute: typeof AmbulanceIndexRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/tracking': {
      id: '/patient/tracking'
      path: '/tracking'
      fullPath: '/patient/tracking'
      preLoaderRoute: typeof PatientTrackingRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/sos': {
      id: '/patient/sos'
      path: '/sos'
      fullPath: '/patient/sos'
      preLoaderRoute: typeof PatientSosRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/preferences': {
      id: '/patient/preferences'
      path: '/preferences'
      fullPath: '/patient/preferences'
      preLoaderRoute: typeof PatientPreferencesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/auth': {
      id: '/patient/auth'
      path: '/auth'
      fullPath: '/patient/auth'
      preLoaderRoute: typeof PatientAuthRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/ai': {
      id: '/patient/ai'
      path: '/ai'
      fullPath: '/patient/ai'
      preLoaderRoute: typeof PatientAiRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/activity': {
      id: '/patient/activity'
      path: '/activity'
      fullPath: '/patient/activity'
      preLoaderRoute: typeof PatientActivityRouteImport
      parentRoute: typeof PatientRoute
    }
    '/hospital/staff': {
      id: '/hospital/staff'
      path: '/staff'
      fullPath: '/hospital/staff'
      preLoaderRoute: typeof HospitalStaffRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/reservations': {
      id: '/hospital/reservations'
      path: '/reservations'
      fullPath: '/hospital/reservations'
      preLoaderRoute: typeof HospitalReservationsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/requests': {
      id: '/hospital/requests'
      path: '/requests'
      fullPath: '/hospital/requests'
      preLoaderRoute: typeof HospitalRequestsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/payments': {
      id: '/hospital/payments'
      path: '/payments'
      fullPath: '/hospital/payments'
      preLoaderRoute: typeof HospitalPaymentsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/emergencies': {
      id: '/hospital/emergencies'
      path: '/emergencies'
      fullPath: '/hospital/emergencies'
      preLoaderRoute: typeof HospitalEmergenciesRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/diagnostics': {
      id: '/hospital/diagnostics'
      path: '/diagnostics'
      fullPath: '/hospital/diagnostics'
      preLoaderRoute: typeof HospitalDiagnosticsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/consultations': {
      id: '/hospital/consultations'
      path: '/consultations'
      fullPath: '/hospital/consultations'
      preLoaderRoute: typeof HospitalConsultationsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/blood': {
      id: '/hospital/blood'
      path: '/blood'
      fullPath: '/hospital/blood'
      preLoaderRoute: typeof HospitalBloodRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/beds': {
      id: '/hospital/beds'
      path: '/beds'
      fullPath: '/hospital/beds'
      preLoaderRoute: typeof HospitalBedsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/analytics': {
      id: '/hospital/analytics'
      path: '/analytics'
      fullPath: '/hospital/analytics'
      preLoaderRoute: typeof HospitalAnalyticsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/ambulances': {
      id: '/hospital/ambulances'
      path: '/ambulances'
      fullPath: '/hospital/ambulances'
      preLoaderRoute: typeof HospitalAmbulancesRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/ambulance/trip': {
      id: '/ambulance/trip'
      path: '/trip'
      fullPath: '/ambulance/trip'
      preLoaderRoute: typeof AmbulanceTripRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/ambulance/splash': {
      id: '/ambulance/splash'
      path: '/splash'
      fullPath: '/ambulance/splash'
      preLoaderRoute: typeof AmbulanceSplashRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/ambulance/profile': {
      id: '/ambulance/profile'
      path: '/profile'
      fullPath: '/ambulance/profile'
      preLoaderRoute: typeof AmbulanceProfileRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/ambulance/notifications': {
      id: '/ambulance/notifications'
      path: '/notifications'
      fullPath: '/ambulance/notifications'
      preLoaderRoute: typeof AmbulanceNotificationsRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/ambulance/navigate': {
      id: '/ambulance/navigate'
      path: '/navigate'
      fullPath: '/ambulance/navigate'
      preLoaderRoute: typeof AmbulanceNavigateRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/ambulance/history': {
      id: '/ambulance/history'
      path: '/history'
      fullPath: '/ambulance/history'
      preLoaderRoute: typeof AmbulanceHistoryRouteImport
      parentRoute: typeof AmbulanceRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/hospitals/': {
      id: '/patient/hospitals/'
      path: '/hospitals'
      fullPath: '/patient/hospitals/'
      preLoaderRoute: typeof PatientHospitalsIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/auth/': {
      id: '/patient/auth/'
      path: '/'
      fullPath: '/patient/auth/'
      preLoaderRoute: typeof PatientAuthIndexRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/hospitals/$id': {
      id: '/patient/hospitals/$id'
      path: '/hospitals/$id'
      fullPath: '/patient/hospitals/$id'
      preLoaderRoute: typeof PatientHospitalsIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/auth/states': {
      id: '/patient/auth/states'
      path: '/states'
      fullPath: '/patient/auth/states'
      preLoaderRoute: typeof PatientAuthStatesRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/splash': {
      id: '/patient/auth/splash'
      path: '/splash'
      fullPath: '/patient/auth/splash'
      preLoaderRoute: typeof PatientAuthSplashRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/signup': {
      id: '/patient/auth/signup'
      path: '/signup'
      fullPath: '/patient/auth/signup'
      preLoaderRoute: typeof PatientAuthSignupRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/onboarding': {
      id: '/patient/auth/onboarding'
      path: '/onboarding'
      fullPath: '/patient/auth/onboarding'
      preLoaderRoute: typeof PatientAuthOnboardingRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/login': {
      id: '/patient/auth/login'
      path: '/login'
      fullPath: '/patient/auth/login'
      preLoaderRoute: typeof PatientAuthLoginRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/forgot': {
      id: '/patient/auth/forgot'
      path: '/forgot'
      fullPath: '/patient/auth/forgot'
      preLoaderRoute: typeof PatientAuthForgotRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/driver-signup': {
      id: '/patient/auth/driver-signup'
      path: '/driver-signup'
      fullPath: '/patient/auth/driver-signup'
      preLoaderRoute: typeof PatientAuthDriverSignupRouteImport
      parentRoute: typeof PatientAuthRoute
    }
    '/patient/auth/account-type': {
      id: '/patient/auth/account-type'
      path: '/account-type'
      fullPath: '/patient/auth/account-type'
      preLoaderRoute: typeof PatientAuthAccountTypeRouteImport
      parentRoute: typeof PatientAuthRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AmbulanceRouteChildren {
  AmbulanceHistoryRoute: typeof AmbulanceHistoryRoute
  AmbulanceNavigateRoute: typeof AmbulanceNavigateRoute
  AmbulanceNotificationsRoute: typeof AmbulanceNotificationsRoute
  AmbulanceProfileRoute: typeof AmbulanceProfileRoute
  AmbulanceSplashRoute: typeof AmbulanceSplashRoute
  AmbulanceTripRoute: typeof AmbulanceTripRoute
  AmbulanceIndexRoute: typeof AmbulanceIndexRoute
}

const AmbulanceRouteChildren: AmbulanceRouteChildren = {
  AmbulanceHistoryRoute: AmbulanceHistoryRoute,
  AmbulanceNavigateRoute: AmbulanceNavigateRoute,
  AmbulanceNotificationsRoute: AmbulanceNotificationsRoute,
  AmbulanceProfileRoute: AmbulanceProfileRoute,
  AmbulanceSplashRoute: AmbulanceSplashRoute,
  AmbulanceTripRoute: AmbulanceTripRoute,
  AmbulanceIndexRoute: AmbulanceIndexRoute,
}

const AmbulanceRouteWithChildren = AmbulanceRoute._addFileChildren(
  AmbulanceRouteChildren,
)

interface HospitalRouteChildren {
  HospitalAmbulancesRoute: typeof HospitalAmbulancesRoute
  HospitalAnalyticsRoute: typeof HospitalAnalyticsRoute
  HospitalBedsRoute: typeof HospitalBedsRoute
  HospitalBloodRoute: typeof HospitalBloodRoute
  HospitalConsultationsRoute: typeof HospitalConsultationsRoute
  HospitalDiagnosticsRoute: typeof HospitalDiagnosticsRoute
  HospitalEmergenciesRoute: typeof HospitalEmergenciesRoute
  HospitalPaymentsRoute: typeof HospitalPaymentsRoute
  HospitalRequestsRoute: typeof HospitalRequestsRoute
  HospitalReservationsRoute: typeof HospitalReservationsRoute
  HospitalStaffRoute: typeof HospitalStaffRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalAmbulancesRoute: HospitalAmbulancesRoute,
  HospitalAnalyticsRoute: HospitalAnalyticsRoute,
  HospitalBedsRoute: HospitalBedsRoute,
  HospitalBloodRoute: HospitalBloodRoute,
  HospitalConsultationsRoute: HospitalConsultationsRoute,
  HospitalDiagnosticsRoute: HospitalDiagnosticsRoute,
  HospitalEmergenciesRoute: HospitalEmergenciesRoute,
  HospitalPaymentsRoute: HospitalPaymentsRoute,
  HospitalRequestsRoute: HospitalRequestsRoute,
  HospitalReservationsRoute: HospitalReservationsRoute,
  HospitalStaffRoute: HospitalStaffRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

interface PatientAuthRouteChildren {
  PatientAuthAccountTypeRoute: typeof PatientAuthAccountTypeRoute
  PatientAuthDriverSignupRoute: typeof PatientAuthDriverSignupRoute
  PatientAuthForgotRoute: typeof PatientAuthForgotRoute
  PatientAuthLoginRoute: typeof PatientAuthLoginRoute
  PatientAuthOnboardingRoute: typeof PatientAuthOnboardingRoute
  PatientAuthSignupRoute: typeof PatientAuthSignupRoute
  PatientAuthSplashRoute: typeof PatientAuthSplashRoute
  PatientAuthStatesRoute: typeof PatientAuthStatesRoute
  PatientAuthIndexRoute: typeof PatientAuthIndexRoute
}

const PatientAuthRouteChildren: PatientAuthRouteChildren = {
  PatientAuthAccountTypeRoute: PatientAuthAccountTypeRoute,
  PatientAuthDriverSignupRoute: PatientAuthDriverSignupRoute,
  PatientAuthForgotRoute: PatientAuthForgotRoute,
  PatientAuthLoginRoute: PatientAuthLoginRoute,
  PatientAuthOnboardingRoute: PatientAuthOnboardingRoute,
  PatientAuthSignupRoute: PatientAuthSignupRoute,
  PatientAuthSplashRoute: PatientAuthSplashRoute,
  PatientAuthStatesRoute: PatientAuthStatesRoute,
  PatientAuthIndexRoute: PatientAuthIndexRoute,
}

const PatientAuthRouteWithChildren = PatientAuthRoute._addFileChildren(
  PatientAuthRouteChildren,
)

interface PatientRouteChildren {
  PatientActivityRoute: typeof PatientActivityRoute
  PatientAiRoute: typeof PatientAiRoute
  PatientAuthRoute: typeof PatientAuthRouteWithChildren
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientPreferencesRoute: typeof PatientPreferencesRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientSosRoute: typeof PatientSosRoute
  PatientTrackingRoute: typeof PatientTrackingRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientHospitalsIdRoute: typeof PatientHospitalsIdRoute
  PatientHospitalsIndexRoute: typeof PatientHospitalsIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientActivityRoute: PatientActivityRoute,
  PatientAiRoute: PatientAiRoute,
  PatientAuthRoute: PatientAuthRouteWithChildren,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientPreferencesRoute: PatientPreferencesRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientSosRoute: PatientSosRoute,
  PatientTrackingRoute: PatientTrackingRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientHospitalsIdRoute: PatientHospitalsIdRoute,
  PatientHospitalsIndexRoute: PatientHospitalsIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AmbulanceRoute: AmbulanceRouteWithChildren,
  AuthRoute: AuthRoute,
  HospitalRoute: HospitalRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
